---
title: "Getting Global"
format: html
---
```{r}
#| label: setup
#| echo: false
#| message: false
source("_chapter-defaults.R")

library(tidyverse)

# path to data
pth_data <- here::here() |> dirname()
pth_apdf <- here::here(pth_data, "__DATA","APDF")

# load APDF airports
apts_pbwg <- readxl::read_xlsx("./data/pbwg-apts.xlsx")
apts_pbwg_noneur <- apts_pbwg |> filter(REG_3 != "EUR") |> select(REG = REG_3, ICAO)
```

```{r}
source("~/RProjects/PBWG-2024-Xian/R/apdf-nice-names.R")

# iterate by hand
apt <- "LTFM"

fn_2023 <- check_zip_content(pth_apdf,"apdf-2023.zip") |> 
    filter(grepl(pattern = apt, x = Name))
ds_2023 <- read_zip(pth_apdf, "apdf-2023.zip", fn_2023$Name) |> 
    trim_apdf_for_pbwg(.sam_id = TRUE) |> 
    make_nice_names_apdf()  |> 
    append_dof()

fn_2024 <- check_zip_content(pth_apdf,"apdf-2024-JanSep.zip") |> 
    filter(grepl(pattern = apt, x = Name))
ds_2024 <- read_zip(pth_apdf, "apdf-2024-JanSep.zip", fn_2024$Name) |> 
    trim_apdf_for_pbwg(.sam_id = TRUE) |> 
    make_nice_names_apdf() |> 
    append_dof()
```

arrivals from / departures to PBWG airports

initialise tofm = list()

```{r}
arrs <- bind_rows(ds_2023, ds_2024) |> filter(PHASE == "ARR") |> 
    filter(ADEP %in% apts_pbwg_noneur$ICAO) |> mutate(ICAO = apt)

deps <- bind_rows(ds_2023, ds_2024) |> filter(PHASE == "DEP") |> 
    filter(ADES %in% apts_pbwg_noneur$ICAO) |> mutate(ICAO = apt)

tofm[[apt]] <- bind_rows(arrs, deps)
```

once done - write out

```{}
tofm <- tofm |> bind_rows()
tofm |> arrow::write_parquet("./data-raw/gfv_20232024p.parquet")
```

========

